fix possible tooltip exception
if it is set to ""

java.lang.IllegalArgumentException: Width and height must be >= 0
Width and height must be >= 0
javax.swing.plaf.basic.BasicHTML.getHTMLBaseline(Unknown Source)
javax.swing.plaf.metal.MetalToolTipUI.paint(Unknown Source)